const Types = {
  HANDLE_SEARCH: "HANDLE_SEARCH",
  REQUEST_SEACH_API: "REQUEST_SEACH_API",
  SUCESS_SEARCH_API: "SUCESS_SEARCH_API",
  ERROR_SEARCH_API: "ERROR_SEARCH_API",
  REQUEST_GENRE_API: "REQUEST_GENRE_API",
  SUCESS_GENRES_API: "SUCESS_GENRES_API",
  REQUEST_MOVIE_API: "REQUEST_MOVIE_API",
  SUCESS_MOVIE_API: "SUCESS_MOVIE_API",
  ERROR_MOVIE_API: "ERROR_MOVIE_API",
  SET_PAGINATION: "SET_PAGINATION"
};

export default Types;
